### ISSUE TITLE
R师傅救救

### ISSUE THREAD

**Issue by GotALeanSip** [RoderickChan/pwncli#33]
报错信息：
Traceback (most recent call last):
  File "/home/saynow/CTF/ISCC/pwn/miyuren/origin/./exp_cli.py", line 9, in <module>
    cli_script()
  File "/home/saynow/Tools/pwncli/pwncli/cli.py", line 217, in cli_script
    cli.main(standalone_mode=False)
  File "/home/saynow/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/saynow/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/saynow/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/saynow/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/saynow/.local/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/saynow/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/saynow/Tools/pwncli/pwncli/commands/cmd_debug.py", line 627, in cli
    _check_set_value(ctx, filename, argv, env, tmux, wsl, gnome, attach_mode,
  File "/home/saynow/Tools/pwncli/pwncli/commands/cmd_debug.py", line 426, in _check_set_value
    ctx.gift['_elf_base'] = ctx.gift.elf.address or get_current_codebase_addr()
  File "/home/saynow/Tools/pwncli/pwncli/utils/cli_misc.py", line 74, in wrapper2
    res = func_call(*args, **kwargs)
  File "/home/saynow/Tools/pwncli/pwncli/utils/cli_misc.py", line 298, in get_current_codebase_addr
    return r['code']
KeyError: 'code'

**Comment by GotALeanSip** [comment]
[二进制.zip](https://github.com/RoderickChan/pwncli/files/11437669/default.zip)
这是出错时的二进制文件

**Comment by RoderickChan** [comment]
> [二进制.zip](https://github.com/RoderickChan/pwncli/files/11437669/default.zip) 这是出错时的二进制文件

已修复
